FROM alexellis2/go-armhf:1.7.4

WORKDIR /go/src/github.com/alexellis/hash-browns/

RUN go get -d -v github.com/gorilla/mux && \
    go get -d -v github.com/prometheus/client_golang/prometheus

COPY server.go .
RUN go build -o server

EXPOSE 8080

CMD ["./server"]
